apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: doc-billing-ingress
  namespace: prod-mspr-ci
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod

spec:
  tls:
  - hosts:
    - billing.louisperdereau.fr
    secretName: hello-app-tls
  rules:
  - host: billing.louisperdereau.fr
    http:
      paths:
      - path: /doc
        backend:
          serviceName: doc-billing-service
          servicePort: 80